"""Every shipped baseline check must name a path the audit actually produces.

A baseline is worth having only if its checks measure real data. A check whose
``path`` names a key no section carries reports ``not_measured`` forever — dead
weight that inflates the "not measured" count and never once judges a tenant.
The engine already has a name for that: ``reason_code == "field_absent"``. A
check whose ``op`` cannot compare the value it finds is ``"incomparable"``.
Both are authoring mistakes, not tenant states, and this test fails on either.

The fixture is the *healthy* tenant (``tests/audit_fixture.py``): every section
carries data, so every well-authored guard is satisfied and every well-authored
path resolves. The one legitimate ``guard_unset`` is drift — the fixture is a
single run with nothing to compare against — so ``guard_unset`` is tolerated
while ``field_absent`` and ``incomparable`` are not.

`docs/baseline-context-paths.md` (regenerated by
``scripts/gen_baseline_paths.py``) is the human listing of the paths this test
enforces against; keep the two in step.
"""

from __future__ import annotations

import pathlib
import tempfile

import pytest

from app.core.baseline import (
    BASELINE_DIR,
    evaluate,
)
from app.reports.generator import build_report_context
from tests.audit_fixture import FULL_AUDIT

# Reason codes that mean "the standard is wrong", not "the tenant is".
AUTHORING_FAULTS = {"field_absent", "incomparable"}


@pytest.fixture(scope="module")
def healthy_context() -> dict:
    tmp = pathlib.Path(tempfile.mkdtemp()) / "Acme_AS" / "2026-01-01_0900"
    tmp.mkdir(parents=True)
    for name, content in FULL_AUDIT.items():
        (tmp / name).write_text(content, encoding="utf-8")
    return build_report_context(
        "Acme AS", "acme.no", tmp, [], lang="no",
        frameworks="all", persist_metrics=False,
    )


def _baseline_ids() -> list[str]:
    return sorted(p.stem for p in BASELINE_DIR.glob("*.json"))


@pytest.mark.parametrize("baseline_id", _baseline_ids())
def test_no_check_names_a_path_the_audit_never_produces(baseline_id, healthy_context):
    """No check may resolve to field_absent/incomparable against a full audit."""
    result = evaluate(baseline_id, healthy_context)
    faults = [
        (c["id"], c["reason_code"], c.get("params", {}))
        for c in result["checks"]
        if c["reason_code"] in AUTHORING_FAULTS
    ]
    assert not faults, (
        f"{baseline_id}: checks reference data the audit does not produce — "
        f"fix the path or drop the check. Offenders: {faults}"
    )


@pytest.mark.parametrize("baseline_id", _baseline_ids())
def test_a_baseline_measures_most_of_itself_on_a_full_audit(baseline_id, healthy_context):
    """A standard that scores almost nothing on a *complete* audit is miscalibrated.

    Against the healthy fixture — where every section carries data — a baseline
    should assess the large majority of its checks. If most come back
    not_measured here, the checks are aimed at signals this audit never
    collects, and the framework is advisory theatre rather than a measurement.
    Drift is the one built-in exception (a single run has nothing to compare).
    """
    result = evaluate(baseline_id, healthy_context)
    total = result["total_checks"]
    assessed = result["assessed"]
    assert assessed >= max(1, round(total * 0.6)), (
        f"{baseline_id}: only {assessed}/{total} checks were measurable on a "
        f"complete audit. Author checks against paths in "
        f"docs/baseline-context-paths.md."
    )


def test_the_path_reference_doc_exists_and_is_populated():
    """Item 1's deliverable: the measurable-path listing is present and real."""
    doc = pathlib.Path(__file__).resolve().parent.parent / "docs" / "baseline-context-paths.md"
    assert doc.is_file(), "docs/baseline-context-paths.md missing — run scripts/gen_baseline_paths.py"
    text = doc.read_text(encoding="utf-8")
    # A few anchor paths every audit produces; if these vanish the generator
    # or the context shape changed and the doc needs regenerating.
    for anchor in ("mfa.registered_pct", "ca.enabled", "admin_roles.global_admin_count"):
        assert f"`{anchor}`" in text, f"{anchor} absent from the path reference"
