#!/usr/bin/env python3
"""Emit ``docs/baseline-context-paths.md`` from the healthy audit fixture.

A baseline check's ``path`` (and its ``measured_when`` guard) is a dotted route
into the report context that ``build_report_context`` produces. A check whose
path names a key the context never carries reports ``not_measured`` — dead
weight on the standard. This script lists every *scalar* leaf path the context
holds when built against ``tests/audit_fixture.py``, so new checks are authored
against real field names rather than guessed ones.

Run from the repo root::

    python scripts/gen_baseline_paths.py

``tests/test_baseline_paths_are_measurable.py`` asserts every shipped baseline
only references paths this listing knows about, so the doc cannot silently rot.
"""

from __future__ import annotations

import pathlib
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.reports.generator import build_report_context  # noqa: E402
from tests.audit_fixture import FULL_AUDIT  # noqa: E402

# Top-level keys that carry raw HTML/text/objects, not measurable scalars.
SKIP_TOP = {
    "file_contents", "results", "SectionStatus", "_severity", "branding",
    "logo_dark", "logo_light", "radar_svg", "recommendations", "compliance",
    "executive_summary", "finding_to_recs", "remediation", "metrics_timeline",
    "compliance_by_category",
    # Raw-text snippets carried for templates.
    "tenant_info", "ext_fwd_warn", "inbox_rule_warn", "risky_users",
    "defender_alerts", "advisor_data", "compliance_policies",
    "app_registrations", "emergency_access", "pim_assignments", "teams_info",
    "teams_settings", "teams_external",
}


def _scalars(obj, prefix: str = "") -> list[tuple[str, str, str]]:
    out: list[tuple[str, str, str]] = []
    if isinstance(obj, dict):
        for key, value in obj.items():
            if not prefix and key in SKIP_TOP:
                continue
            out += _scalars(value, f"{prefix}.{key}" if prefix else key)
    elif isinstance(obj, (list, tuple)):
        pass  # a list is not addressable by a comparison op
    else:
        rendered = repr(obj) if isinstance(obj, str) else str(obj)
        if len(rendered) > 48:
            rendered = rendered[:45] + "..."
        out.append((prefix, type(obj).__name__, rendered))
    return out


def build_context() -> dict:
    tmp = pathlib.Path(tempfile.mkdtemp()) / "Acme_AS" / "2026-01-01_0900"
    tmp.mkdir(parents=True)
    for name, content in FULL_AUDIT.items():
        (tmp / name).write_text(content, encoding="utf-8")
    return build_report_context(
        "Acme AS", "acme.no", tmp, [], lang="no",
        frameworks="all", persist_metrics=False,
    )


def render(rows: list[tuple[str, str, str]]) -> str:
    groups: dict[str, list[tuple[str, str, str]]] = {}
    for path, typ, val in rows:
        groups.setdefault(path.split(".")[0], []).append((path, typ, val))

    out = [
        "<!-- GENERATED by scripts/gen_baseline_paths.py — do not edit by hand. -->",
        "# Baseline context paths — what a check can measure",
        "",
        "A baseline check's `path` (and its `measured_when` guard) is a dotted",
        "route into the report context that `build_report_context`",
        "(`app/reports/generator.py`) produces. A check whose `path` names a key",
        "the section never carries reports **not_measured** — dead weight on the",
        "standard. This file lists every *scalar* leaf path the context holds when",
        "built against the healthy audit fixture (`tests/audit_fixture.py`), so new",
        "checks are authored against real data, not guessed field names.",
        "",
        "Rules of thumb:",
        "",
        "- Guard every check with the section's `*.has_data` (or a specific",
        "  `*.measured` / `*.coverage_known`) flag. Without a guard, an unread",
        "  section scores as a failure and hands the customer a task nobody looked",
        "  at — the one mistake `app/core/baseline.py` exists to prevent.",
        "- A list path is **not** addressable by a comparison op — a check compares",
        "  one scalar. The count fields (`*_count`, `total`, `enabled`, …) are the",
        "  handle onto a list.",
        "- The value column is the fixture's *healthy* value, not a threshold.",
        "",
        "Regenerate with `python scripts/gen_baseline_paths.py`.",
        "",
    ]
    for top in sorted(groups):
        out += [f"## `{top}`", "", "| path | type | fixture value |", "| --- | --- | --- |"]
        for path, typ, val in groups[top]:
            out.append(f"| `{path}` | {typ} | `{val.replace('|', chr(92) + '|')}` |")
        out.append("")
    return "\n".join(out) + "\n"


def main() -> None:
    rows = _scalars(build_context())
    target = ROOT / "docs" / "baseline-context-paths.md"
    target.write_text(render(rows), encoding="utf-8")
    groups = {p.split(".")[0] for p, _, _ in rows}
    print(f"wrote {target.relative_to(ROOT)} — {len(rows)} scalar paths, {len(groups)} sections")


if __name__ == "__main__":
    main()
